# Generated by Django 5.2.6 on 2026-09-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('caps', 'Caps'), ('left_chest', 'Left chest'), ('jacket_back', 'Jacket back'), ('patches', 'Patches'), ('vector', 'Vector')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/')),
                ('meta', models.CharField(blank=True, help_text="Short line, e.g. 'cap front · 4,120 st'", max_length=120)),
                ('showcase_tag', models.CharField(blank=True, help_text="e.g. 'Cap front · foam'", max_length=60)),
                ('placement', models.CharField(blank=True, max_length=80)),
                ('fabric', models.CharField(blank=True, max_length=80)),
                ('stitches', models.PositiveIntegerField(blank=True, null=True)),
                ('formats', models.CharField(blank=True, max_length=80)),
                ('turnaround', models.CharField(blank=True, max_length=40)),
                ('show_on_home', models.BooleanField(default=False, help_text='Include in the home page sew-out showcase')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+1 (512) 555-0148', max_length=40)),
                ('email', models.EmailField(default='hello@sedigitizer.com', max_length=254)),
                ('orders_email', models.EmailField(default='orders@sedigitizer.com', max_length=254)),
                ('hours', models.CharField(default='Live chat 24/7 · Studio 8am–8pm CT', max_length=120)),
                ('announcement', models.CharField(default='4-hour standard turnaround', max_length=80)),
                ('patch_production_note', models.CharField(default='8–12 day production', max_length=80)),
                ('patch_min_quantity', models.PositiveIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
