# Generated by Django 5.2.6 on 2026-09-19 14:35

from django.conf import settings
from django.db import migrations, models


def seed_recipient(apps, schema_editor):
    """Existing installs keep getting alerts at the address already configured in .env."""
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(order_notification_emails="").update(
        order_notification_emails=settings.STAFF_NOTIFY_EMAIL
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_on_new_order',
            field=models.BooleanField(default=True, help_text='Send an alert whenever a customer places an order.', verbose_name='email me about new orders'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='order_notification_emails',
            field=models.CharField(blank=True, help_text='Where new-order alerts are sent. Separate several addresses with commas.', max_length=500, verbose_name='order alerts go to'),
        ),
        migrations.RunPython(seed_recipient, migrations.RunPython.noop),
    ]
