# Generated by Django 5.2.6 on 2026-09-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_notify_on_new_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, help_text='Shown on the contact page and used for the map, e.g. 12 Loom St, Austin, TX 78701.', max_length=250, verbose_name='studio address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Optional. Paste the src from Google Maps > Share > Embed a map. Leave empty to map the address above.', max_length=500, verbose_name='custom map embed URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_map',
            field=models.BooleanField(default=True, verbose_name='show the map on the contact page'),
        ),
    ]
