# Generated by Django 5.2.6 on 2026-09-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_address_sitesettings_map_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_name',
            field=models.CharField(default='Scarlett Embroidery', help_text='Used for the map pin label, so the listing shows on the contact page map.', max_length=120),
        ),
    ]
