# Generated by Django 5.2.6 on 2026-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_business_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=40, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "portfolio categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=300, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=300, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=300, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="pinterest_url",
            field=models.URLField(blank=True, max_length=300, verbose_name="Pinterest"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tiktok_url",
            field=models.URLField(blank=True, max_length=300, verbose_name="TikTok"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_url",
            field=models.URLField(blank=True, max_length=300, verbose_name="WhatsApp"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="x_url",
            field=models.URLField(
                blank=True, max_length=300, verbose_name="X (Twitter)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(blank=True, max_length=300, verbose_name="YouTube"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="category",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
