# Generated by Django 5.2.6 on 2026-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_seed_portfolio_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeforeAfter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("embroidery", "Embroidery digitizing"),
                            ("vector", "Vector art"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("before_image", models.ImageField(upload_to="before-after/")),
                ("after_image", models.ImageField(upload_to="before-after/")),
                ("before_label", models.CharField(default="Before", max_length=20)),
                ("after_label", models.CharField(default="After", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "before / after",
                "verbose_name_plural": "before / after pairs",
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("embroidery", "Embroidery digitizing"),
                            ("vector", "Vector art"),
                            ("patches", "Patches"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="services/")),
                ("caption", models.CharField(blank=True, max_length=120)),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("home_hero", "Home — hero photo"),
                            ("about_hero", "About — main photo"),
                            ("about_story", "About — story photo"),
                            ("about_studio", "About — studio photo"),
                            ("about_team", "About — team photo"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="site/")),
            ],
        ),
        migrations.AddField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo or logo shown with the review.",
                upload_to="testimonials/",
                verbose_name="photo",
            ),
        ),
    ]
