# Generated by Django 5.2.6 on 2026-10-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_media_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteimage",
            name="slot",
            field=models.CharField(
                choices=[
                    ("home_hero", "Home — hero photo"),
                    ("about_hero", "About — main photo"),
                    ("about_story", "About — story photo"),
                    ("about_studio", "About — studio photo"),
                    ("about_team", "About — team photo"),
                    ("blog_default", "Blog — default cover (posts without one)"),
                    ("portfolio_default", "Portfolio — fallback sew-out photo"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
