# Generated by Django 5.2.6 on 2026-10-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_siteimage_cta_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="SewOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Recommended 1000 × 1000 px.",
                        upload_to="sewouts/",
                        verbose_name="photo",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Left-chest logo on polo", max_length=120
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True,
                        help_text="Client or shop name (optional).",
                        max_length=80,
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Pique polo · 3.5 in · 8,200 stitches",
                        max_length=160,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "client sew-out",
                "ordering": ["sort_order", "-id"],
            },
        ),
        migrations.AddField(
            model_name="testimonial",
            name="work_photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo of the sewn result, shown on top of the review (about 800 × 600 px).",
                upload_to="testimonials/work/",
                verbose_name="sew-out photo",
            ),
        ),
    ]
