# Generated by Django 5.2.6 on 2026-09-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='console_theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text='Each admin picks their own look for the console.', max_length=10, verbose_name='admin console theme'),
        ),
    ]
