# Generated by Django 5.2.6 on 2026-09-17 00:38

import apps.orders.models
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='from price / piece')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'patch categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('digitizing', 'Digitizing'), ('vector', 'Vector Art')], max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['service', 'sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='TurnaroundOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hours', models.PositiveIntegerField(help_text='Target hours from a complete order')),
                ('surcharge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'hours'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('service', models.CharField(choices=[('digitizing', 'Digitizing'), ('vector', 'Vector Art'), ('patches', 'Patches')], default='digitizing', max_length=20)),
                ('contact_name', models.CharField(max_length=120, verbose_name='name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='email')),
                ('design_name', models.CharField(max_length=160, verbose_name='design name / PO reference')),
                ('fabric', models.CharField(blank=True, max_length=60)),
                ('placement', models.CharField(blank=True, max_length=60)),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='height (in)')),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='width (in)')),
                ('formats', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True, verbose_name='instructions / notes')),
                ('estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'In queue'), ('in_progress', 'In production'), ('awaiting_approval', 'Awaiting approval'), ('revision', 'Revision requested'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.pricingtier', verbose_name='design type')),
                ('turnaround', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.turnaroundoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Order placed'), ('status', 'Status changed'), ('price', 'Price set'), ('file', 'Files added'), ('message', 'Message'), ('note', 'Internal note'), ('approved', 'Proof approved'), ('revision', 'Revision requested'), ('payment', 'Payment')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('artwork', 'Artwork'), ('proof', 'Sew-out proof'), ('deliverable', 'Final file')], default='artwork', max_length=20)),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='/app/private_media'), upload_to=apps.orders.models.order_file_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backing', models.CharField(choices=[('iron_on', 'Iron-on'), ('velcro', 'Velcro (hook & loop)'), ('adhesive', 'Adhesive'), ('sew_on', 'Sew-on')], default='iron_on', max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('width_in', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='width (in)')),
                ('height_in', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='height (in)')),
                ('shipping_name', models.CharField(max_length=120, verbose_name='recipient name')),
                ('shipping_phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('address_line1', models.CharField(max_length=200, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='address line 2')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state / province')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('country', models.CharField(default='United States', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patch_orders', to='orders.patchcategory', verbose_name='patch category')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patch', to='orders.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_orde_custome_413d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'due_at'], name='orders_orde_status_2c2ef8_idx'),
        ),
    ]
