# Generated by Django 5.2.6, plus card content for the standard digitizing plans.

from django.db import migrations, models

# So an existing site shows the new pricing cards straight away. Everything here
# is editable afterwards in Console -> Settings -> Pricing.
PLAN_PRESETS = {
    "Left chest": {
        "plan_name": "Base",
        "ribbon": "BASE",
        "features": "\n".join(
            [
                "Left chest / hat logo",
                "PDF proof before delivery",
                "All required machine formats",
                'Up to 5" x 5" (W x H)',
            ]
        ),
        "is_highlighted": False,
    },
    "Full back": {
        "plan_name": "Premium",
        "ribbon": "EXTRA",
        "features": "\n".join(
            [
                "Full back logo",
                "PDF proof before delivery",
                "All required machine formats",
                'Larger than 5" x 5" (W x H)',
            ]
        ),
        "is_highlighted": True,
    },
    "Complex design": {
        "plan_name": "Performance",
        "ribbon": "FULL",
        "features": "\n".join(
            [
                "Complex logo design",
                "PDF proof before delivery",
                "All required machine formats",
                'Larger than 5" x 5" (W x H)',
            ]
        ),
        "is_highlighted": False,
    },
}


def fill_plan_cards(apps, schema_editor):
    PricingTier = apps.get_model("orders", "PricingTier")
    for name, preset in PLAN_PRESETS.items():
        PricingTier.objects.filter(service="digitizing", name=name, features="").update(**preset)


def clear_plan_cards(apps, schema_editor):
    PricingTier = apps.get_model("orders", "PricingTier")
    PricingTier.objects.update(plan_name="", ribbon="", features="", is_highlighted=False)


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderdraft_orderdraftfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingtier",
            name="features",
            field=models.TextField(
                blank=True, help_text="What the plan includes — one per line, shown as the card's list."
            ),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="is_highlighted",
            field=models.BooleanField(
                default=False,
                help_text="Lifts the card and marks it as the popular choice.",
                verbose_name="highlight this plan",
            ),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="plan_name",
            field=models.CharField(
                blank=True,
                help_text="Shown on the pricing card, e.g. Base. Defaults to the name.",
                max_length=40,
                verbose_name="plan name",
            ),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="ribbon",
            field=models.CharField(
                blank=True, help_text="Corner flag on the card, e.g. BASE. Leave empty for none.", max_length=16
            ),
        ),
        migrations.RunPython(fill_plan_cards, clear_plan_cards),
    ]
