# Generated by Django 5.2.6 on 2026-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_pricingtier_features_pricingtier_is_highlighted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_quote",
            field=models.BooleanField(
                default=False,
                help_text="A request for a price — the customer never sees an estimate.",
                verbose_name="quote request",
            ),
        ),
        migrations.AddField(
            model_name="patchcategory",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="What the patch includes — one per line, shown as the card's list.",
            ),
        ),
        migrations.AddField(
            model_name="patchcategory",
            name="is_highlighted",
            field=models.BooleanField(
                default=False,
                help_text="Lifts the card and marks it as the popular choice.",
                verbose_name="highlight this plan",
            ),
        ),
        migrations.AddField(
            model_name="patchcategory",
            name="ribbon",
            field=models.CharField(
                blank=True,
                help_text="Corner flag on the card, e.g. POPULAR. Leave empty for none.",
                max_length=16,
            ),
        ),
    ]
