# Generated by Django 5.2.6 on 2026-10-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_site_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_country',
            field=models.CharField(blank=True, help_text='Country code from the trusted Cloudflare request header, when available.', max_length=60, verbose_name='customer country code'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='customer IP address'),
        ),
    ]
